# Generated by Django 4.1.3 on 2023-08-13 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_genders', to='API_Handler.lookup'),
        ),
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to='API_Handler.lookup'),
        ),
    ]
