# Generated by Django 4.1.3 on 2023-08-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0002_alter_users_gender_alter_users_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='CNIC',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='ProfilePicture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_genders', to='API_Handler.lookup'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateTimeField()),
                ('diagnosis_notes', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Handler.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Handler.patient')),
            ],
        ),
    ]
