# Generated by Django 4.1.3 on 2023-08-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0003_patient_cnic_users_profilepicture_alter_users_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BMI',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='BloodGroup',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Height',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='MedicalDiagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='NursingDiagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='UserId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='API_Handler.users'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Weight',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=50),
        ),
    ]
