# Generated by Django 4.2 on 2023-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0004_alter_patient_bmi_alter_patient_bloodgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='ProfilePicture',
        ),
        migrations.AddField(
            model_name='users',
            name='IsAuthenticatedByGoogle',
            field=models.BooleanField(default=False),
        ),
    ]
