# Generated by Django 4.2 on 2023-09-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0005_remove_users_profilepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='IsAuthenticatedByGoogle',
            field=models.BooleanField(null=True),
        ),
    ]
