# Generated by Django 4.2 on 2023-09-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0006_alter_users_isauthenticatedbygoogle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('activityType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_type', to='API_Handler.lookup')),
                ('patient_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='API_Handler.patient')),
            ],
        ),
    ]
