# Generated by Django 4.2 on 2023-09-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0007_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
