# Generated by Django 4.2 on 2023-10-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0008_rename_patient_id_activity_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='IsVerified',
            field=models.BooleanField(default=False),
        ),
    ]
