# Generated by Django 4.2.5 on 2023-10-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0008_rename_patient_id_activity_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Cnic',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Bio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Domain',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Experience',
            field=models.SmallIntegerField(null=True),
        ),
    ]
