# Generated by Django 4.1.3 on 2023-11-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0009_users_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='CurrentMedication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Hospitalization',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='MajorIllness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='MedicalAllergy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='PainLocation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='PainSeverity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='PastMedication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Supplements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Surgeries',
            field=models.TextField(blank=True),
        ),
    ]
