# Generated by Django 4.2.5 on 2023-10-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0009_doctor_cnic_alter_doctor_bio_alter_doctor_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
