# Generated by Django 4.1.3 on 2023-11-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0010_patient_currentmedication_patient_hospitalization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='BloodGroup',
            new_name='bloodGroup',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='CurrentMedication',
            new_name='currentMedication',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='AdmitDiBP',
            new_name='distolicBp',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='AdmitBPM',
            new_name='heartBeat',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Hospitalization',
            new_name='hospitalization',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='MajorIllness',
            new_name='majorIllness',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='MedicalAllergy',
            new_name='medicalAllergy',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='AdmitO2',
            new_name='o2Level',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='PainLocation',
            new_name='painLocation',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='PainSeverity',
            new_name='painSeverity',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='PastMedication',
            new_name='pastMedication',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Supplements',
            new_name='supplements',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Surgeries',
            new_name='surgeries',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='AdmitSysBP',
            new_name='systolicBp',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='AdmitTemp',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Gender',
            new_name='gender',
        ),
    ]
