# Generated by Django 4.1.3 on 2023-11-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0012_remove_patient_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='gender',
            new_name='Gender',
        ),
    ]
