# Generated by Django 4.2.5 on 2023-11-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0012_rename_cnic_users_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
