# Generated by Django 4.2.5 on 2023-11-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API_Handler", "0013_alter_users_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Hospital Name", max_length=30)),
                (
                    "ownerid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API_Handler.users",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctor",
            name="HospitalId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="API_Handler.hospital",
            ),
        ),
    ]
