# Generated by Django 4.2.5 on 2023-11-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0014_hospital_doctor_hospitalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Fname',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Lname',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to='API_Handler.lookup'),
        ),
    ]
