# Generated by Django 4.2.5 on 2023-11-08 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0015_alter_users_fname_alter_users_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='Bio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='Experience',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Handler.lookup'),
        ),
    ]
