# Generated by Django 4.1.3 on 2023-11-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0013_rename_gender_users_gender'),
        ('API_Handler', '0016_alter_nurse_bio_alter_nurse_experience_and_more'),
    ]

    operations = [
    ]
