# Generated by Django 4.1.3 on 2023-11-13 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0018_rename_activitytype_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(),
        ),
    ]
