# Generated by Django 4.1.3 on 2023-11-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0019_alter_patient_admission_date_alter_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carevitals',
            old_name='distolic_bp',
            new_name='diastolic_bp',
        ),
        migrations.RenameField(
            model_name='carevitals',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='medicationschedule',
            old_name='med_id',
            new_name='med',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='distolic_bp',
            new_name='diastolic_bp',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='Ward',
        ),
        migrations.AddField(
            model_name='ward',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_Handler.hospital'),
        ),
        migrations.CreateModel(
            name='NurseWard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Handler.nurse')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Handler.ward')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalWard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Handler.hospital')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Handler.ward')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorWard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Handler.doctor')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Handler.ward')),
            ],
        ),
    ]
