# Generated by Django 4.1.3 on 2023-11-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0020_rename_distolic_bp_carevitals_diastolic_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_domain', to='API_Handler.lookup'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_type', to='API_Handler.lookup'),
        ),
    ]
