# Generated by Django 4.1.3 on 2023-11-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0021_alter_doctor_domain_alter_nurse_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='hospital',
        ),
        migrations.AddField(
            model_name='nurse',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_Handler.hospital'),
        ),
    ]
