# Generated by Django 4.1.3 on 2023-11-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0022_remove_ward_hospital_nurse_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='o2_evel',
            new_name='o2_level',
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_Handler.hospital'),
        ),
        migrations.DeleteModel(
            name='HospitalWard',
        ),
    ]
