# Generated by Django 4.1.3 on 2023-11-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0023_rename_o2_evel_patient_o2_level_patient_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
    ]
