# Generated by Django 4.1.3 on 2023-11-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0024_remove_doctor_hospital_remove_nurse_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_Handler.hospital'),
        ),
    ]
