# Generated by Django 4.1.3 on 2023-11-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Handler', '0025_ward_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
