# Generated by Django 4.1.3 on 2023-11-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API_Handler", "0026_users_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.AddField(
            model_name="users",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gender_type",
                to="API_Handler.lookup",
            ),
        ),
    ]
